# data is a volume-only container for keeping the mysql and magento filesystemproduction
# volumes in one place.
data:
  image: busybox
  volumes:
    - ../app:/usr/share/nginx/html:rw

mysql:
  env_file:
    - ./prod/mysql/mysql.env
  image: mysql:5.6
  volumes:
    - /var/lib/mysql/data/
  expose:
    - "3306"

phpfpm:
  build: ./prod/phpfpm
  expose:
    - 9000
  volumes_from:
    - data
  links:
    - mysql

nginx:
  image: nginx:1.9.8
  ports:
    - "80:80"
  volumes:
    - ./prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - data
  links:
    - phpfpm
